FROM php:7.2-fpm

### PHP Extension ###

RUN apt update

RUN apt install -y \
    libxml2-dev \
    zlib1g-dev \
    libjpeg-dev \
    libpng-dev \
    libwebp-dev \
    libfreetype6-dev

RUN docker-php-ext-configure gd \
    --with-freetype-dir=/usr/lib/x86_64-linux-gnu/ \
    --with-png-dir=/usr/lib/x86_64-linux-gnu/ \
    --with-webp-dir=/usr/lib/x86_64-linux-gnu/ \
    --with-jpeg-dir=/usr/lib/x86_64-linux-gnu/

RUN docker-php-ext-install \
    mbstring \
    pdo \
    pdo_mysql \
    mysqli \
    tokenizer \
    xml \
    bcmath \
    zip \
    gd \
    exif \
    pcntl

### XDebug ###

RUN pecl install xdebug-2.6.1 && \
    docker-php-ext-enable xdebug

### Composer ###

RUN curl -s http://getcomposer.org/installer | php && \
    mv composer.phar /usr/local/bin/composer

### Timezone ###

ARG TZ=UTC
ENV TZ ${TZ}
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

### Node JS ###

RUN apt-get install -y curl software-properties-common
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -
RUN apt-get install -y nodejs

### Opcache ###

RUN docker-php-ext-install opcache
COPY ./opcache.ini /usr/local/etc/php/conf.d/opcache.ini

### Cron ###

RUN apt install -y cron
COPY ./crontab /etc/cron.d
RUN chmod -R 0644 /etc/cron.d

### Supervisor ###

RUN apt install -y supervisor
COPY ./supervisor.conf /etc/supervisor/supervisor.conf
RUN chmod -R 0644 /etc/supervisor/supervisor.conf

### Final ###

COPY ./user.ini /usr/local/etc/php/conf.d

RUN groupmod -o -g 1000 www-data && \
    usermod -o -u 1000 -g www-data www-data

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisor.conf"]
