version: '2'

volumes:
  mysql:
    driver: local
  redis:
    driver: local

networks:
  laravel:
    driver: "bridge"

services:

  nginx:
    build:
      context: docker/nginx
      args:
        - SERVER_NAME=${NGINX_SERVER_NAME}
    volumes:
      - ${APP_CODE_PATH}:/var/www/html
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
      - ${NGINX_HOST_HTTPS_PORT}:443
    networks:
      - laravel

  php:
    build:
      context: docker/php
      dockerfile: Dockerfile.dev
      args:
        - TZ=${TIMEZONE}
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - ${APP_CODE_PATH}:/var/www/html
    networks:
      - laravel

  mysql:
    build: docker/mysql
    volumes:
      - mysql:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TIMEZONE}
    networks:
      - laravel

  redis:
    image: redis
    volumes:
      - redis:/data
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
    volumes:
      - ${PMA_PHP_INI}:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
    ports:
      - ${PMA_PORT}:80
    networks:
      - laravel
