version: '2'

volumes:
  mysql:
    driver: local
  redis:
    driver: local

networks:
  laravel:
    driver: "bridge"

services:

  nginx:
    build:
      context: docker/nginx
      args:
        - SERVER_NAME=${NGINX_SERVER_NAME}
    volumes:
      - ${APP_CODE_PATH}:/var/www/html:cached
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
      - ${NGINX_HOST_HTTPS_PORT}:443
    networks:
      - laravel

  php:
    build:
      context: docker/php
      args:
        - TZ=${TIMEZONE}
    volumes:
      - ${APP_CODE_PATH}:/var/www/html:cached
    networks:
      - laravel

  mysql:
    build: docker/mysql
    volumes:
      - mysql:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TIMEZONE}
    networks:
      - laravel

  redis:
    image: redis
    volumes:
      - redis:/data
    networks:
      - laravel
