version: '3'

volumes:
  mysql:
    driver: local

services:

  nginx:
    image: nginx:latest
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    links:
      - php

  php:
    build:
      context: docker/php
      dockerfile: Dockerfile.dev
      args:
        - TZ=${TIMEZONE}
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
    links:
      - mysql

  mysql:
    image: mariadb:latest
    volumes:
      - mysql:/var/lib/mysql/
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASSWORD}
    ports:
      - ${PMA_PORT}:80