version: '3'

volumes:
  db:
  redis:

services:

  php:
    build:
      context: docker/php
      args:
        - PHP_CONTAINER_VERSION=${PHP_CONTAINER_VERSION}
        - TZ=${TIMEZONE}
    volumes:
      - ${APP_CODE_PATH}:/var/www/html:cached
    restart: on-failure

  nginx:
    build:
      context: docker/nginx
      args:
        - SERVER_NAME=${NGINX_SERVER_NAME}
    volumes:
      - ${APP_CODE_PATH}:/var/www/html:cached
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
      - ${NGINX_HOST_HTTPS_PORT}:443
    depends_on:
      - php
    restart: on-failure

  db:
    build: docker/db
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - TZ=${TIMEZONE}
    volumes:
      - db:/var/lib/mysql
    restart: on-failure

  redis:
    image: redis
    volumes:
      - redis:/data
    restart: on-failure

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
    volumes:
      - ${PMA_PHP_INI}:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
    ports:
      - ${PMA_PORT}:80
    depends_on:
      - db
    restart: on-failure
