version: '3'

volumes:
  mysql:
  pgsql:
  redis:

services:
  php:
    build: ./php
    volumes:
      - ../:/var/www/html:cached
    extra_hosts:
      - dockerhost:${DOCKER_HOST_IP}

  nginx:
    build: ./nginx
    volumes:
      - ../:/var/www/html:cached
      # - ./certs/localhost.pem:/etc/nginx/ssl/nginx.crt
      # - ./certs/localhost-key.pem:/etc/nginx/ssl/nginx.key
    ports:
      - ${NGINX_HTTP_PORT}:80/tcp
      - ${NGINX_HTTPS_PORT}:443/tcp

  pgsql:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgsql:/var/lib/postgresql/data

  redis:
    image: redis
    volumes:
      - redis:/data
