version: '3'

volumes:
  mysql:
  pgsql:
  redis:

services:
  php-fpm:
    build: ./php
    volumes:
      - ../:/var/www/html:cached

  nginx:
    build: ./nginx
    volumes:
      - ../:/var/www/html:cached
    ports:
      - ${NGINX_HTTP_PORT}:80/tcp
      - ${NGINX_HTTPS_PORT}:443/tcp

  pgsql:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgsql:/var/lib/postgresql/data

  redis:
    image: redis
    volumes:
      - redis:/data
