version: '3'

volumes:
  pgsql-data:
  mysql-data:
  mysql-files-data:
  redis-data:

services:
  php:
    build: ./images/php/8.1-laravel
    volumes:
      - ../:/var/www/html:cached
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
    extra_hosts:
      - dockerhost:${DOCKER_HOST_IP}

  scheduler:
    build: ./images/php/8.1-laravel
    entrypoint: "cron -f"
    volumes:
      - ../:/var/www/html:cached

  worker:
    build: ./images/php/8.1-laravel
    command: "php artisan queue:work"
    volumes:
      - ../:/var/www/html:cached

  nginx:
    image: nginx
    volumes:
      - ../:/var/www/html:cached
      - ./config/nginx/default.conf.template:/etc/nginx/templates/default.conf.template
      - ./certs/localhost.pem:/etc/nginx/ssl/nginx.crt
      - ./certs/localhost-key.pem:/etc/nginx/ssl/nginx.key
    environment:
      - PHP_HOST=php
    ports:
      - ${NGINX_HTTP_PORT}:80/tcp
      - ${NGINX_HTTPS_PORT}:443/tcp

  pgsql:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgsql-data:/var/lib/postgresql/data

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
      - mysql-files-data:/var/lib/mysql-files
      - ./config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

  redis:
    image: redis
    volumes:
      - redis-data:/data

  adminer:
    image: adminer
    ports:
      - ${ADMINER_PORT}:8080/tcp
