version: '3'

volumes:
  mysql:
  pgsql:
  redis:

services:
  php:
    build:
      context: ./php
      args:
        - PHP_CONTAINER_VERSION=${PHP_CONTAINER_VERSION}
        - TZ=${TIMEZONE}
    volumes:
      - ${APP_CODE_PATH}:/var/www/html:cached

  nginx:
    build:
      context: ./nginx
      args:
        - SERVER_NAME=${NGINX_SERVER_NAME}
        - PHP_HOST=php
    volumes:
      - ${APP_CODE_PATH}:/var/www/html:cached
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80/tcp
      - ${NGINX_HOST_HTTPS_PORT}:443/tcp

  mysql:
    image: mysql
    command:
      - mysqld
      - --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql

  pgsql:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgsql:/var/lib/postgresql/data

  redis:
    image: redis
    volumes:
      - redis:/data

  adminer:
    image: adminer
    ports:
      - ${ADMINER_PORT}:8080/tcp
