version: '3'

volumes:
  db:
  redis:

services:
  db:
    build: ./db
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - TZ=${TIMEZONE}
    volumes:
      - db:/var/lib/mysql

  php:
    build:
      context: ./php
      args:
        - PHP_CONTAINER_VERSION=${PHP_CONTAINER_VERSION}
        - TZ=${TIMEZONE}
    volumes:
      - ${APP_CODE_PATH}:/var/www/html:cached
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
      args:
        - SERVER_NAME=${NGINX_SERVER_NAME}
        - PHP_HOST=php
    volumes:
      - ${APP_CODE_PATH}:/var/www/html:cached
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
      - ${NGINX_HOST_HTTPS_PORT}:443
    depends_on:
      - php

  redis:
    image: redis
    volumes:
      - redis:/data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
    volumes:
      - ${PMA_PHP_INI}:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
    ports:
      - ${PMA_PORT}:80
